language: node_js
node_js:
- '0.12'
script: true
after_success:
  - echo "myvar: ${VAR_X}!!"
  - echo "othervar: $VAR_X!!"
  - echo something/${VAR_X}/nina
  - env
env:
  global:
  - VAR_X=foo
  - VAR_Y=bar
  - secure: fraen6XFugn2P5jufxQQGaQd7N21j1zoCS+vC5Qod08uzHMx6rKYbVCt4INisS+KrkWncNy27XgHMtMOH0Qz1M5BmG8TcAneoGQGp0HweblgzBBoMSvopw8mdn+nFfV2+WdYJYI9FgOO9HlbeeM27LD4elGt05yVzLfKoHswP0E=
